# 2023 - 03 - Classification - Homework

In [2]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [21]:
cols = [
    'Make',
    'Model',
    'Year',
    'Engine HP',
    'Engine Cylinders',
    'Transmission Type',
    'Vehicle Style',
    'highway MPG',
    'city mpg',
    'MSRP'
]

In [22]:
df = df[cols]
df.head()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,highway MPG,city mpg,MSRP
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,Coupe,26,19,46135
1,BMW,1 Series,2011,300.0,6.0,MANUAL,Convertible,28,19,40650
2,BMW,1 Series,2011,300.0,6.0,MANUAL,Coupe,28,20,36350
3,BMW,1 Series,2011,230.0,6.0,MANUAL,Coupe,28,18,29450
4,BMW,1 Series,2011,230.0,6.0,MANUAL,Convertible,28,18,34500

In [23]:
df.columns = df.columns.str.replace(' ', '_').str.lower()
df.head()

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,highway_mpg,city_mpg,msrp
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,Coupe,26,19,46135
1,BMW,1 Series,2011,300.0,6.0,MANUAL,Convertible,28,19,40650
2,BMW,1 Series,2011,300.0,6.0,MANUAL,Coupe,28,20,36350
3,BMW,1 Series,2011,230.0,6.0,MANUAL,Coupe,28,18,29450
4,BMW,1 Series,2011,230.0,6.0,MANUAL,Convertible,28,18,34500

In [24]:
df = df.fillna(0)

In [25]:
df.rename(columns={'msrp': 'price'}, inplace=True)

In [26]:
df.head()

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,highway_mpg,city_mpg,price
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,Coupe,26,19,46135
1,BMW,1 Series,2011,300.0,6.0,MANUAL,Convertible,28,19,40650
2,BMW,1 Series,2011,300.0,6.0,MANUAL,Coupe,28,20,36350
3,BMW,1 Series,2011,230.0,6.0,MANUAL,Coupe,28,18,29450
4,BMW,1 Series,2011,230.0,6.0,MANUAL,Convertible,28,18,34500

In [27]:
df["above_average"] = (df["price"] > df["price"].mean()).astype(int)
df.head()

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,highway_mpg,city_mpg,price,above_average
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,Coupe,26,19,46135,1
1,BMW,1 Series,2011,300.0,6.0,MANUAL,Convertible,28,19,40650,1
2,BMW,1 Series,2011,300.0,6.0,MANUAL,Coupe,28,20,36350,0
3,BMW,1 Series,2011,230.0,6.0,MANUAL,Coupe,28,18,29450,0
4,BMW,1 Series,2011,230.0,6.0,MANUAL,Convertible,28,18,34500,0

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
n = 0.2

In [31]:
df_full_train, df_test = train_test_split(df, test_size=n, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=n/(1-n), random_state=42)

In [32]:
df_train.shape, df_val.shape, df_test.shape

((7148, 11), (2383, 11), (2383, 11))

In [34]:
y_full_train = df_full_train.above_average.values
y_train = df_train.above_average.values 
y_val = df_val.above_average.values 
y_test = df_test.above_average.values

In [35]:
del df_train['price']
del df_val['price']
del df_test['price']
del df_full_train['price']

del df_train['above_average']
del df_val['above_average']
del df_test['above_average']
del df_full_train['above_average']

In [36]:
from sklearn.metrics import mutual_info_score

In [37]:
cat_cols = df_full_train.select_dtypes(include=['object']).columns.tolist()
cat_cols

['make', 'model', 'transmission_type', 'vehicle_style']

In [38]:
num_cols = df_full_train.select_dtypes(include=['number']).columns.tolist()
num_cols

['year', 'engine_hp', 'engine_cylinders', 'highway_mpg', 'city_mpg']

In [39]:
mutual_info_score?

Signature: mutual_info_score(labels_true, labels_pred, *, contingency=None)
Docstring:
Mutual Information between two clusterings.

The Mutual Information is a measure of the similarity between two labels
of the same data. Where :math:`|U_i|` is the number of the samples
in cluster :math:`U_i` and :math:`|V_j|` is the number of the
samples in cluster :math:`V_j`, the Mutual Information
between clusterings :math:`U` and :math:`V` is given as:

.. math::

    MI(U,V)=\sum_{i=1}^{|U|} \sum_{j=1}^{|V|} \frac{|U_i\cap V_j|}{N}
    \log\frac{N|U_i \cap V_j|}{|U_i||V_j|}

This metric is independent of the absolute values of the labels:
a permutation of the class or cluster label values won't change the
score value in any way.

This metric is furthermore symmetric: switching :math:`U` (i.e
``label_true``) with :math:`V` (i.e. ``label_pred``) will return the
same score value. This can be useful to measure the agreement of two
independent label assignments strategies on the same dataset when the
real ground truth is not known.

Read more in the :ref:`User Guide <mutual_info_score>`.

Parameters
----------
labels_true : array-like of shape (n_samples,), dtype=integral
    A clustering of the data into disjoint subsets, called :math:`U` in
    the above formula.

labels_pred : array-like of shape (n_samples,), dtype=integral
    A clustering of the data into disjoint subsets, called :math:`V` in
    the above formula.

contingency : {array-like, sparse matrix} of shape             (n_classes_true, n_classes_pred), default=None
    A contingency matrix given by the
    :func:`~sklearn.metrics.cluster.contingency_matrix` function. If value
    is ``None``, it will be computed, otherwise the given value is used,
    with ``labels_true`` and ``labels_pred`` ignored.

Returns
-------
mi : float
   Mutual information, a non-negative value, measured in nats using the
   natural logarithm.

See Also
--------
adjusted_mutual_info_score : Adjusted against chance Mutual Information.
normalized_mutual_info_score : Normalized Mutual Information.

Notes
-----
The logarithm used is the natural logarithm (base-e).

Examples
--------
>>> from sklearn.metrics import mutual_info_score
>>> labels_true = [0, 1, 1, 0, 1, 0]
>>> labels_pred = [0, 1, 0, 0, 1, 1]
>>> mutual_info_score(labels_true, labels_pred)
0.0566
File:      ~/.local/lib/python3.12/site-packages/sklearn/metrics/cluster/_supervised.py
Type:      function

In [43]:
for col in cat_cols:
    mi = mutual_info_score(df_full_train[col], y_full_train)
    print(f'{col}: {mi:.2f}')

make: 0.24
model: 0.46
transmission_type: 0.02
vehicle_style: 0.08

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction import DictVectorizer

In [45]:
dv = DictVectorizer(sparse=False)

In [46]:
train_dicts = df_train[cat_cols + num_cols].to_dict(orient='records')
val_dicts = df_val[cat_cols + num_cols].to_dict(orient='records')
test_dicts = df_test[cat_cols + num_cols].to_dict(orient='records')

In [48]:
dv.fit(train_dicts)

DictVectorizer(sparse=False)

In [52]:
dv.get_feature_names_out()

array(['city_mpg', 'engine_cylinders', 'engine_hp', 'highway_mpg',
       'make=Acura', 'make=Alfa Romeo', 'make=Aston Martin', 'make=Audi',
       'make=BMW', 'make=Bentley', 'make=Bugatti', 'make=Buick',
       'make=Cadillac', 'make=Chevrolet', 'make=Chrysler', 'make=Dodge',
       'make=FIAT', 'make=Ferrari', 'make=Ford', 'make=GMC',
       'make=Genesis', 'make=HUMMER', 'make=Honda', 'make=Hyundai',
       'make=Infiniti', 'make=Kia', 'make=Lamborghini', 'make=Land Rover',
       'make=Lexus', 'make=Lincoln', 'make=Lotus', 'make=Maserati',
       'make=Maybach', 'make=Mazda', 'make=McLaren', 'make=Mercedes-Benz',
       'make=Mitsubishi', 'make=Nissan', 'make=Oldsmobile',
       'make=Plymouth', 'make=Pontiac', 'make=Porsche',
       'make=Rolls-Royce', 'make=Saab', 'make=Scion', 'make=Spyker',
       'make=Subaru', 'make=Suzuki', 'make=Tesla', 'make=Toyota',
       'make=Volkswagen', 'make=Volvo', 'model=1 Series', 'model=100',
       'model=124 Spider', 'model=190-Class', 'model=2', 'model=2 Series',
       'model=200', 'model=200SX', 'model=240', 'model=240SX', 'model=3',
       'model=3 Series', 'model=3 Series Gran Turismo', 'model=300',
       'model=300-Class', 'model=3000GT', 'model=300M', 'model=300ZX',
       'model=323', 'model=350-Class', 'model=350Z', 'model=360',
       'model=370Z', 'model=4 Series', 'model=4 Series Gran Coupe',
       'model=400-Class', 'model=420-Class', 'model=456M',
       'model=458 Italia', 'model=4C', 'model=4Runner', 'model=5',
       'model=5 Series', 'model=5 Series Gran Turismo', 'model=500',
       'model=500-Class', 'model=500L', 'model=500X', 'model=500e',
       'model=550', 'model=560-Class', 'model=57', 'model=570S',
       'model=575M', 'model=599', 'model=6', 'model=6 Series',
       'model=6 Series Gran Coupe', 'model=600-Class', 'model=6000',
       'model=612 Scaglietti', 'model=62', 'model=626', 'model=7 Series',
       'model=740', 'model=760', 'model=780', 'model=8 Series',
       'model=80', 'model=850', 'model=9-2X', 'model=9-3',
       'model=9-3 Griffin', 'model=9-4X', 'model=9-5', 'model=9-7X',
       'model=90', 'model=900', 'model=9000', 'model=911', 'model=928',
       'model=929', 'model=940', 'model=944', 'model=960', 'model=968',
       'model=A3', 'model=A4', 'model=A5', 'model=A6', 'model=A7',
       'model=A8', 'model=ALPINA B6 Gran Coupe', 'model=ALPINA B7',
       'model=AMG GT', 'model=ATS', 'model=ATS Coupe', 'model=Acadia',
       'model=Acadia Limited', 'model=Accent', 'model=Acclaim',
       'model=Accord', 'model=Accord Crosstour', 'model=Accord Hybrid',
       'model=Accord Plug-In Hybrid', 'model=Achieva',
       'model=ActiveHybrid 5', 'model=ActiveHybrid 7',
       'model=ActiveHybrid X6', 'model=Aerio', 'model=Aerostar',
       'model=Alero', 'model=Allante', 'model=Altima',
       'model=Altima Hybrid', 'model=Amanti', 'model=Armada',
       'model=Arnage', 'model=Aspen', 'model=Aspire', 'model=Astro',
       'model=Astro Cargo', 'model=Aurora', 'model=Avalanche',
       'model=Avalon', 'model=Avalon Hybrid', 'model=Avenger',
       'model=Aventador', 'model=Aveo', 'model=Aviator', 'model=Axxess',
       'model=Azera', 'model=Aztek', 'model=Azure', 'model=Azure T',
       'model=B-Class Electric Drive', 'model=B-Series',
       'model=B-Series Pickup', 'model=B-Series Truck',
       'model=B9 Tribeca', 'model=BRZ', 'model=Baja', 'model=Beetle',
       'model=Beetle Convertible', 'model=Beretta',
       'model=Black Diamond Avalanche', 'model=Blackwood', 'model=Blazer',
       'model=Bonneville', 'model=Borrego', 'model=Boxster',
       'model=Bravada', 'model=Breeze', 'model=Bronco', 'model=Bronco II',
       'model=Brooklands', 'model=Brougham', 'model=C-Class',
       'model=C-Max Hybrid', 'model=C/K 1500 Series',
       'model=C/K 2500 Series', 'model=C30', 'model=C43 AMG', 'model=C70',
       'model=C8', 'model=CC', 'model=CL', 'model=CL-Class',
       'model=CLA-Class', 'model=CLK-Class', 'model=CLS-Class',
       'model=CR-V', 'model=CR-Z', 'model=CT6', 'model=CTS',
       'model=CTS Coupe', 'model=CTS Wagon', 'model=CTS-V',
       'model=CTS-V Coupe', 'model=CTS-V Wagon', 'model=CX-3',
       'model=CX-5', 'model=CX-7', 'model=CX-9', 'model=Cabrio',
       'model=Cabriolet', 'model=Cadenza', 'model=Caliber',
       'model=Camaro', 'model=Camry', 'model=Camry Hybrid',
       'model=Camry Solara', 'model=Canyon', 'model=Caprice',
       'model=Captiva Sport', 'model=Caravan', 'model=Carrera GT',
       'model=Cascada', 'model=Catera', 'model=Cavalier', 'model=Cayenne',
       'model=Cayman', 'model=Cayman S', 'model=Celebrity',
       'model=Celica', 'model=Century', 'model=Challenger',
       'model=Charger', 'model=Chevy Van', 'model=City Express',
       'model=Civic', 'model=Civic CRX', 'model=Civic del Sol',
       'model=Classic', 'model=Cobalt', 'model=Colorado', 'model=Colt',
       'model=Concorde', 'model=Continental',
       'model=Continental Flying Spur',
       'model=Continental Flying Spur Speed', 'model=Continental GT',
       'model=Continental GT Speed',
       'model=Continental GT Speed Convertible', 'model=Continental GTC',
       'model=Continental GTC Speed', 'model=Continental Supersports',
       'model=Continental Supersports Convertible', 'model=Contour',
       'model=Corniche', 'model=Corolla', 'model=Corolla iM',
       'model=Corrado', 'model=Corvette', 'model=Corvette Stingray',
       'model=Coupe', 'model=Cressida', 'model=Crossfire',
       'model=Crosstour', 'model=Crosstrek', 'model=Crown Victoria',
       'model=Cruze', 'model=Cruze Limited', 'model=Cube',
       'model=Custom Cruiser', 'model=Cutlass', 'model=Cutlass Calais',
       'model=Cutlass Ciera', 'model=Cutlass Supreme', 'model=DB9',
       'model=DB9 GT', 'model=DBS', 'model=DTS', 'model=Dakota',
       'model=Dart', 'model=Dawn', 'model=Daytona', 'model=DeVille',
       'model=Defender', 'model=Diablo', 'model=Diamante',
       'model=Discovery', 'model=Discovery Series II',
       'model=Discovery Sport', 'model=Durango', 'model=Dynasty',
       'model=E-150', 'model=E-250', 'model=E-Class',
       'model=E-Series Van', 'model=E-Series Wagon', 'model=E55 AMG',
       'model=ECHO', 'model=ES 250', 'model=ES 300', 'model=ES 300h',
       'model=EX', 'model=EX35', 'model=Eclipse', 'model=Eclipse Spyder',
       'model=Edge', 'model=Eighty-Eight', 'model=Eighty-Eight Royale',
       'model=Elantra', 'model=Elantra Coupe', 'model=Elantra GT',
       'model=Elantra Touring', 'model=Eldorado', 'model=Electra',
       'model=Element', 'model=Elise', 'model=Enclave', 'model=Encore',
       'model=Endeavor', 'model=Entourage', 'model=Envision',
       'model=Envoy', 'model=Envoy XL', 'model=Envoy XUV', 'model=Eos',
       'model=Equator', 'model=Equinox', 'model=Equus', 'model=Escalade',
       'model=Escalade ESV', 'model=Escalade EXT',
       'model=Escalade Hybrid', 'model=Escape', 'model=Escape Hybrid',
       'model=Escort', 'model=Esprit', 'model=Esteem', 'model=EuroVan',
       'model=Evora', 'model=Excel', 'model=Exige', 'model=Expedition',
       'model=Explorer', 'model=Explorer Sport',
       'model=Explorer Sport Trac', 'model=Expo', 'model=Express',
       'model=Express Cargo', 'model=F-150', 'model=F-150 Heritage',
       'model=F-150 SVT Lightning', 'model=F-250', 'model=F12 Berlinetta',
       'model=F430', 'model=FF', 'model=FJ Cruiser', 'model=FR-S',
       'model=FX', 'model=FX35', 'model=FX45', 'model=FX50',
       'model=Festiva', 'model=Fiesta', 'model=Firebird', 'model=Fit',
       'model=Five Hundred', 'model=Fleetwood', 'model=Flex',
       'model=Flying Spur', 'model=Focus', 'model=Focus ST',
       'model=Forenza', 'model=Forester', 'model=Forte', 'model=Fox',
       'model=Freelander', 'model=Freestar', 'model=Freestyle',
       'model=Frontier', 'model=Fusion', 'model=Fusion Hybrid',
       'model=G Convertible', 'model=G Coupe', 'model=G Sedan',
       'model=G-Class', 'model=G20', 'model=G3', 'model=G35', 'model=G37',
       'model=G37 Convertible', 'model=G37 Coupe', 'model=G37 Sedan',
       'model=G5', 'model=G6', 'model=G8', 'model=G80', 'model=GL-Class',
       'model=GLA-Class', 'model=GLC-Class', 'model=GLE-Class',
       'model=GLE-Class Coupe', 'model=GLI', 'model=GLK-Class',
       'model=GLS-Class', 'model=GS 200t', 'model=GS 300', 'model=GS 350',
       'model=GS 400', 'model=GS 430', 'model=GS 450h', 'model=GS 460',
       'model=GT', 'model=GT-R', 'model=GTI', 'model=GTO', 'model=GX 460',
       'model=GX 470', 'model=Galant', 'model=Gallardo', 'model=Genesis',
       'model=Genesis Coupe', 'model=Ghibli', 'model=Ghost',
       'model=Ghost Series II', 'model=Golf', 'model=Golf Alltrack',
       'model=Golf GTI', 'model=Golf R', 'model=Golf SportWagen',
       'model=GranSport', 'model=GranTurismo',
       'model=GranTurismo Convertible', 'model=Grand Am',
       'model=Grand Caravan', 'model=Grand Prix', 'model=Grand Vitara',
       'model=Grand Voyager', 'model=H3', 'model=H3T', 'model=HHR',
       'model=HR-V', 'model=HS 250h', 'model=Highlander',
       'model=Highlander Hybrid', 'model=Horizon', 'model=Huracan',
       'model=I30', 'model=I35', 'model=ILX', 'model=ILX Hybrid',
       'model=IS 200t', 'model=IS 250', 'model=IS 250 C', 'model=IS 300',
       'model=IS 350', 'model=IS 350 C', 'model=IS F', 'model=Impala',
       'model=Impala Limited', 'model=Imperial', 'model=Impreza',
       'model=Impreza WRX', 'model=Insight', 'model=Integra',
       'model=Intrepid', 'model=Intrigue', 'model=J30', 'model=JX',
       'model=Jetta', 'model=Jetta GLI', 'model=Jetta Hybrid',
       'model=Jetta SportWagen', 'model=Jimmy', 'model=Journey',
       'model=Juke', 'model=Justy', 'model=K900', 'model=Kizashi',
       'model=LFA', 'model=LHS', 'model=LR2', 'model=LR3', 'model=LR4',
       'model=LS', 'model=LS 400', 'model=LS 430', 'model=LS 460',
       'model=LS 600h L', 'model=LSS', 'model=LTD Crown Victoria',
       'model=LX 450', 'model=LX 470', 'model=LX 570', 'model=LaCrosse',
       'model=Lancer', 'model=Lancer Evolution', 'model=Lancer Sportback',
       'model=Land Cruiser', 'model=Laser', 'model=Le Baron',
       'model=Le Mans', 'model=LeSabre', 'model=Leaf', 'model=Legacy',
       'model=Legend', 'model=Levante', 'model=Loyale', 'model=Lucerne',
       'model=Lumina', 'model=Lumina Minivan', 'model=M', 'model=M-Class',
       'model=M2', 'model=M3', 'model=M30', 'model=M35', 'model=M37',
       'model=M4', 'model=M45', 'model=M5', 'model=M56', 'model=M6',
       'model=M6 Gran Coupe', 'model=MDX', 'model=MKC', 'model=MKS',
       'model=MKT', 'model=MKX', 'model=MKZ', 'model=MKZ Hybrid',
       'model=MP4-12C', 'model=MPV', 'model=MR2', 'model=MR2 Spyder',
       'model=MX-3', 'model=MX-5 Miata', 'model=MX-6', 'model=Macan',
       'model=Magnum', 'model=Malibu', 'model=Malibu Classic',
       'model=Malibu Hybrid', 'model=Malibu Limited', 'model=Malibu Maxx',
       'model=Mark LT', 'model=Mark VII', 'model=Mark VIII',
       'model=Matrix', 'model=Maxima', 'model=Maybach',
       'model=Mazdaspeed 3', 'model=Mazdaspeed MX-5 Miata',
       'model=Mazdaspeed Protege', 'model=Metris', 'model=Metro',
       'model=Mighty Max Pickup', 'model=Millenia', 'model=Mirage',
       'model=Mirage G4', 'model=Model S', 'model=Monaco',
       'model=Montana', 'model=Montana SV6', 'model=Monte Carlo',
       'model=Montero', 'model=Montero Sport', 'model=Mulsanne',
       'model=Murano', 'model=Murano CrossCabriolet', 'model=Murcielago',
       'model=Mustang', 'model=Mustang SVT Cobra', 'model=NSX',
       'model=NV200', 'model=NX', 'model=NX 200t', 'model=NX 300h',
       'model=Navajo', 'model=Navigator', 'model=Neon',
       'model=New Beetle', 'model=New Yorker', 'model=Ninety-Eight',
       'model=Nitro', 'model=Odyssey', 'model=Omni', 'model=Optima',
       'model=Optima Hybrid', 'model=Outback', 'model=Outlander',
       'model=Outlander Sport', 'model=PT Cruiser', 'model=Pacifica',
       'model=Panamera', 'model=Park Avenue', 'model=Paseo',
       'model=Passat', 'model=Passport', 'model=Pathfinder',
       'model=Phaeton', 'model=Phantom', 'model=Phantom Coupe',
       'model=Phantom Drophead Coupe', 'model=Pickup', 'model=Pilot',
       'model=Precis', 'model=Prelude', 'model=Previa', 'model=Prius',
       'model=Prius Prime', 'model=Prius c', 'model=Prius v',
       'model=Prizm', 'model=Probe', 'model=Protege', 'model=Protege5',
       'model=Prowler', 'model=Q3', 'model=Q40', 'model=Q45', 'model=Q5',
       'model=Q50', 'model=Q60 Convertible', 'model=Q60 Coupe',
       'model=Q7', 'model=Q70', 'model=QX', 'model=QX4', 'model=QX50',
       'model=QX56', 'model=QX60', 'model=QX70', 'model=QX80',
       'model=Quattroporte', 'model=Quest', 'model=R-Class', 'model=R32',
       'model=R8', 'model=RAM 150', 'model=RAM 250', 'model=RAV4',
       'model=RAV4 EV', 'model=RAV4 Hybrid', 'model=RC 200t',
       'model=RC 300', 'model=RC 350', 'model=RDX', 'model=RL',
       'model=RLX', 'model=RS 4', 'model=RS 5', 'model=RS 7', 'model=RSX',
       'model=RX 300', 'model=RX 330', 'model=RX 350', 'model=RX 400h',
       'model=RX 450h', 'model=RX-7', 'model=RX-8', 'model=Rabbit',
       'model=Raider', 'model=Rainier', 'model=Rally Wagon',
       'model=Ram 50 Pickup', 'model=Ram Cargo', 'model=Ram Pickup 1500',
       'model=Ram Van', 'model=Ram Wagon', 'model=Ramcharger',
       'model=Range Rover', 'model=Range Rover Evoque',
       'model=Range Rover Sport', 'model=Ranger', 'model=Rapide',
       'model=Rapide S', 'model=Reatta', 'model=Regal', 'model=Regency',
       'model=Rendezvous', 'model=Reno', 'model=Reventon',
       'model=Ridgeline', 'model=Rio', 'model=Riviera',
       'model=Roadmaster', 'model=Rogue', 'model=Rogue Select',
       'model=Rondo', 'model=Routan', 'model=S-10', 'model=S-10 Blazer',
       'model=S-15', 'model=S-15 Jimmy', 'model=S-Class', 'model=S2000',
       'model=S3', 'model=S4', 'model=S40', 'model=S5', 'model=S6',
       'model=S60', 'model=S60 Cross Country', 'model=S7', 'model=S70',
       'model=S8', 'model=S80', 'model=S90', 'model=SC 300',
       'model=SC 400', 'model=SC 430', 'model=SL-Class',
       'model=SLC-Class', 'model=SLK-Class', 'model=SLR McLaren',
       'model=SLS AMG', 'model=SLS AMG GT',
       'model=SLS AMG GT Final Edition', 'model=SLX', 'model=SQ5',
       'model=SRT Viper', 'model=SRX', 'model=STS', 'model=STS-V',
       'model=SVX', 'model=SX4', 'model=Safari', 'model=Safari Cargo',
       'model=Samurai', 'model=Santa Fe', 'model=Santa Fe Sport',
       'model=Savana', 'model=Savana Cargo', 'model=Scoupe',
       'model=Sebring', 'model=Sedona', 'model=Sentra', 'model=Sephia',
       'model=Sequoia', 'model=Seville', 'model=Shadow',
       'model=Shelby GT350', 'model=Shelby GT500', 'model=Sidekick',
       'model=Sienna', 'model=Sierra 1500', 'model=Sierra 1500 Classic',
       'model=Sierra 1500 Hybrid', 'model=Sierra 1500HD',
       'model=Sierra C3', 'model=Sierra Classic 1500', 'model=Sigma',
       'model=Silhouette', 'model=Silver Seraph', 'model=Silverado 1500',
       'model=Silverado 1500 Classic', 'model=Silverado 1500 Hybrid',
       'model=Skylark', 'model=Solstice', 'model=Sonata',
       'model=Sonata Hybrid', 'model=Sonic', 'model=Sonoma',
       'model=Sorento', 'model=Soul', 'model=Soul EV', 'model=Spark',
       'model=Spark EV', 'model=Spectra', 'model=Spirit',
       'model=Sportage', 'model=Sportvan', 'model=Spyder', 'model=Stanza',
       'model=Stealth', 'model=Stratus', 'model=Suburban',
       'model=Sunbird', 'model=Sundance', 'model=Sunfire', 'model=Supra',
       'model=Swift', 'model=Syclone', 'model=T100', 'model=TL',
       'model=TLX', 'model=TSX', 'model=TSX Sport Wagon', 'model=TT',
       'model=TTS', 'model=Tacoma', 'model=Tahoe', 'model=Tahoe Hybrid',
       'model=Tahoe Limited/Z71', 'model=Taurus', 'model=Taurus X',
       'model=Tempo', 'model=Tercel', 'model=Terrain', 'model=Terraza',
       'model=Thunderbird', 'model=Tiburon', 'model=Tiguan',
       'model=Titan', 'model=Toronado', 'model=Torrent', 'model=Touareg',
       'model=Touareg 2', 'model=Town Car', 'model=Town and Country',
       'model=Tracker', 'model=TrailBlazer', 'model=TrailBlazer EXT',
       'model=Trans Sport', 'model=Transit Connect',
       'model=Transit Wagon', 'model=Traverse', 'model=Trax',
       'model=Tribeca', 'model=Tribute', 'model=Tribute Hybrid',
       'model=Truck', 'model=Tucson', 'model=Tundra', 'model=Typhoon',
       'model=Uplander', 'model=V12 Vanquish', 'model=V12 Vantage',
       'model=V12 Vantage S', 'model=V40', 'model=V50', 'model=V60',
       'model=V60 Cross Country', 'model=V70', 'model=V8 Vantage',
       'model=Van', 'model=Vanagon', 'model=Vandura', 'model=Vanquish',
       'model=Vanwagon', 'model=Veloster', 'model=Venture', 'model=Venza',
       'model=Veracruz', 'model=Verano', 'model=Verona', 'model=Versa',
       'model=Versa Note', 'model=Veyron 16.4', 'model=Vibe',
       'model=Vigor', 'model=Viper', 'model=Virage', 'model=Vitara',
       'model=Voyager', 'model=WRX', 'model=Windstar',
       'model=Windstar Cargo', 'model=Wraith', 'model=X-90', 'model=X1',
       'model=X3', 'model=X4', 'model=X5', 'model=X5 M', 'model=X6',
       'model=X6 M', 'model=XC', 'model=XC60', 'model=XC70', 'model=XC90',
       'model=XG300', 'model=XG350', 'model=XL-7', 'model=XL7',
       'model=XLR', 'model=XLR-V', 'model=XT', 'model=XT5', 'model=XTS',
       'model=XV Crosstrek', 'model=Xterra', 'model=Yaris',
       'model=Yaris iA', 'model=Yukon', 'model=Yukon Denali',
       'model=Yukon Hybrid', 'model=Yukon XL', 'model=Z3', 'model=Z4',
       'model=Z4 M', 'model=Z8', 'model=ZDX', 'model=allroad',
       'model=allroad quattro', 'model=e-Golf', 'model=i-MiEV',
       'model=i3', 'model=iA', 'model=iQ', 'model=tC', 'model=xA',
       'model=xB', 'model=xD', 'transmission_type=AUTOMATED_MANUAL',
       'transmission_type=AUTOMATIC', 'transmission_type=DIRECT_DRIVE',
       'transmission_type=MANUAL', 'transmission_type=UNKNOWN',
       'vehicle_style=2dr Hatchback', 'vehicle_style=2dr SUV',
       'vehicle_style=4dr Hatchback', 'vehicle_style=4dr SUV',
       'vehicle_style=Cargo Minivan', 'vehicle_style=Cargo Van',
       'vehicle_style=Convertible', 'vehicle_style=Convertible SUV',
       'vehicle_style=Coupe', 'vehicle_style=Crew Cab Pickup',
       'vehicle_style=Extended Cab Pickup',
       'vehicle_style=Passenger Minivan', 'vehicle_style=Passenger Van',
       'vehicle_style=Regular Cab Pickup', 'vehicle_style=Sedan',
       'vehicle_style=Wagon', 'year'], dtype=object)

In [50]:
X_train = dv.transform(train_dicts)
X_val = dv.transform(val_dicts)
X_test = dv.transform(test_dicts)

In [51]:
X_train[:5]

array([[  15.,    6.,  225., ...,    0.,    0., 2011.],
       [  17.,    6.,  276., ...,    0.,    0., 2009.],
       [  12.,   10.,  570., ...,    0.,    0., 2012.],
       [  20.,    4.,  200., ...,    0.,    0., 2016.],
       [  20.,    4.,  158., ...,    0.,    0., 2009.]], shape=(5, 943))

In [53]:
model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)

In [54]:
model.fit(X_train, y_train)

LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')

In [55]:
y_pred = model.predict_proba(X_val)[:, 1]

In [61]:
round((y_val == (y_pred >= 0.5).astype(int)).mean(), 2)

np.float64(0.93)