# Old homework for learning

In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("data/bank-full.csv", sep=";")
df.head(), df.shape

(   age           job  marital  education default  balance housing loan  \
 0   58    management  married   tertiary      no     2143     yes   no
 1   44    technician   single  secondary      no       29     yes   no
 2   33  entrepreneur  married  secondary      no        2     yes  yes
 3   47   blue-collar  married    unknown      no     1506     yes   no
 4   33       unknown   single    unknown      no        1      no   no

    contact  day month  duration  campaign  pdays  previous poutcome   y
 0  unknown    5   may       261         1     -1         0  unknown  no
 1  unknown    5   may       151         1     -1         0  unknown  no
 2  unknown    5   may        76         1     -1         0  unknown  no
 3  unknown    5   may        92         1     -1         0  unknown  no
 4  unknown    5   may       198         1     -1         0  unknown  no  ,
 (45211, 17))

In [7]:
cols = ["age",
"job",
"marital",
"education",
"balance",
"housing",
"contact",
"day",
"month",
"duration",
"campaign",
"pdays",
"previous",
"poutcome",
"y"]

In [24]:
df = df[cols]
df.head()

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,2143,yes,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,29,yes,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,2,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,1506,yes,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,1,no,unknown,5,may,198,1,-1,0,unknown,no

In [25]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

We dont have any missing values in this database

In [26]:
df["education"].value_counts()

education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

In [29]:
cat_cols = df.select_dtypes("object").columns.to_list()
len(cat_cols)

8

In [30]:
num_cols = df.select_dtypes("number").columns.to_list()
len(num_cols)

7

In [36]:
corr_matrix = df[num_cols].corr()
corr_matrix

               age   balance       day  duration  campaign     pdays  previous
age       1.000000  0.097783 -0.009120 -0.004648  0.004760 -0.023758  0.001288
balance   0.097783  1.000000  0.004503  0.021560 -0.014578  0.003435  0.016674
day      -0.009120  0.004503  1.000000 -0.030206  0.162490 -0.093044 -0.051710
duration -0.004648  0.021560 -0.030206  1.000000 -0.084570 -0.001565  0.001203
campaign  0.004760 -0.014578  0.162490 -0.084570  1.000000 -0.088628 -0.032855
pdays    -0.023758  0.003435 -0.093044 -0.001565 -0.088628  1.000000  0.454820
previous  0.001288  0.016674 -0.051710  0.001203 -0.032855  0.454820  1.000000

In [44]:
max_corr = 0
max_pair = None

for i, col in enumerate(num_cols):
    for j in range(i):
        if abs(corr_matrix.iloc[i, j]) > max_corr:
            max_corr = abs(corr_matrix.iloc[i, j])
            max_pair = (corr_matrix.index[i], corr_matrix.columns[j])   
            #print(f"{corr_matrix.index[i]} and {corr_matrix.columns[j]}: {corr_matrix.iloc[i, j]}") 
    
print(f"The most correlated columns are `{max_pair[0]}` and `{max_pair[1]}` with a correlation of {max_corr}")

The most correlated columns are `previous` and `pdays` with a correlation of 0.4548196354805043

In [46]:
df["y"] = (df["y"] == "yes").astype(int)

/tmp/ipykernel_22332/4008710147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"] = (df["y"] == "yes").astype(int)

In [47]:
df.head()

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,2143,yes,unknown,5,may,261,1,-1,0,unknown,0
1,44,technician,single,secondary,29,yes,unknown,5,may,151,1,-1,0,unknown,0
2,33,entrepreneur,married,secondary,2,yes,unknown,5,may,76,1,-1,0,unknown,0
3,47,blue-collar,married,unknown,1506,yes,unknown,5,may,92,1,-1,0,unknown,0
4,33,unknown,single,unknown,1,no,unknown,5,may,198,1,-1,0,unknown,0